apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chula-sso-mock
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-example
    server: {{ .Values.spec.destination.server }}
  project: gitops-example
  source:
    path: chula-sso-mock
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}
