apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: An example applications of gitops by samithiwat
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
