apiVersion: v1
kind: Secret
metadata:
  name: example-apps-repo-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: example-apps-repo-config
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
stringData:
  name: Gitops Example Repository
  project: gitops-example
  type: git
  url: git@github.com:thinc-org/thinc-gitops-example.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
